# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main-window.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1205, 780)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        MainWindow.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/image/image/logo-large.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("font-family:Segoe UI")
        self.style = QtWidgets.QWidget(MainWindow)
        self.style.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.style.setStyleSheet("#style {\n"
"    background-color:#fff\n"
"}\n"
"QLineEdit {\n"
"    background: #FFFFFF;\n"
"    border-radius: 4px;\n"
"    color : #50565f;\n"
"    padding-left:16px;\n"
"    padding-right:16px;\n"
"    font-size:15px;\n"
"    border:1px solid transparent\n"
"    \n"
"}\n"
"QLineEdit:hover , QLineEdit:focus {\n"
"    border: 1px solid #e74725;    \n"
"}\n"
"QPushButton:pressed   {\n"
"    padding-bottom:1px\n"
"}\n"
"#user_setting {\n"
"    border-radius:22px;\n"
"    border:1px solid #D3D7DF\n"
"}\n"
"\n"
"#sidebar_menu QPushButton{\n"
"    border:none;\n"
"}\n"
"#sidebar {\n"
"    background-color: rgb(255, 255, 255);\n"
"}\n"
"QWidget #chat_sidebar {\n"
"    border-right:1px solid  #e0e0e0\n"
"}\n"
"\n"
"QWidget #chat_nav_user {\n"
"    border-bottom:1px solid  #e0e0e0\n"
"}\n"
"QWidget#chat_input {\n"
"    border-top:1px solid  #e0e0e0\n"
"}\n"
"QWidget #friend_chat_card{\n"
"    border-radius:4px;\n"
"}\n"
"#friend_chat_card:hover , #friend_chat_card:focus{\n"
"\n"
"    background-color:rgb(245, 245, 245);\n"
"}\n"
"\n"
"#sidebar_menu  QPushButton:hover {\n"
"    background-color:#f5f5f5\n"
"}\n"
"\n"
"")
        self.style.setObjectName("style")
        self.hboxlayout = QtWidgets.QHBoxLayout(self.style)
        self.hboxlayout.setContentsMargins(0, 0, 0, 0)
        self.hboxlayout.setSpacing(0)
        self.hboxlayout.setObjectName("hboxlayout")
        self.container = QtWidgets.QWidget(self.style)
        self.container.setStyleSheet("")
        self.container.setObjectName("container")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.container)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_content = QtWidgets.QWidget(self.container)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.main_content.setFont(font)
        self.main_content.setStyleSheet("")
        self.main_content.setObjectName("main_content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.main_content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.sidebar = QtWidgets.QWidget(self.main_content)
        self.sidebar.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sidebar.setStyleSheet("#sibar {\n"
"    background-color: rgb(243, 108, 37);\n"
"}\n"
"")
        self.sidebar.setObjectName("sidebar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.sidebar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.sidebar_menu = QtWidgets.QWidget(self.sidebar)
        self.sidebar_menu.setMinimumSize(QtCore.QSize(80, 0))
        self.sidebar_menu.setMaximumSize(QtCore.QSize(80, 16777215))
        self.sidebar_menu.setStyleSheet("background-color: #f5f5f5;")
        self.sidebar_menu.setObjectName("sidebar_menu")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.sidebar_menu)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sidebar_menu_content = QtWidgets.QWidget(self.sidebar_menu)
        self.sidebar_menu_content.setObjectName("sidebar_menu_content")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.sidebar_menu_content)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.chat_link = QtWidgets.QPushButton(self.sidebar_menu_content)
        self.chat_link.setMinimumSize(QtCore.QSize(80, 80))
        self.chat_link.setMaximumSize(QtCore.QSize(80, 80))
        self.chat_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.chat_link.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icon/icon/icon-messages-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.chat_link.setIcon(icon1)
        self.chat_link.setIconSize(QtCore.QSize(32, 32))
        self.chat_link.setObjectName("chat_link")
        self.verticalLayout_3.addWidget(self.chat_link)
        self.member_link = QtWidgets.QPushButton(self.sidebar_menu_content)
        self.member_link.setMinimumSize(QtCore.QSize(80, 80))
        self.member_link.setMaximumSize(QtCore.QSize(80, 80))
        self.member_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.member_link.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-member-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.member_link.setIcon(icon2)
        self.member_link.setIconSize(QtCore.QSize(32, 32))
        self.member_link.setObjectName("member_link")
        self.verticalLayout_3.addWidget(self.member_link)
        self.todo_list_link = QtWidgets.QPushButton(self.sidebar_menu_content)
        self.todo_list_link.setMinimumSize(QtCore.QSize(80, 80))
        self.todo_list_link.setMaximumSize(QtCore.QSize(80, 80))
        self.todo_list_link.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.todo_list_link.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icon/icon/icon-todo-list-active.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.todo_list_link.setIcon(icon3)
        self.todo_list_link.setIconSize(QtCore.QSize(32, 32))
        self.todo_list_link.setObjectName("todo_list_link")
        self.verticalLayout_3.addWidget(self.todo_list_link)
        self.verticalLayout_2.addWidget(self.sidebar_menu_content, 0, QtCore.Qt.AlignTop)
        self.user_btn = QtWidgets.QPushButton(self.sidebar_menu)
        self.user_btn.setMinimumSize(QtCore.QSize(80, 80))
        self.user_btn.setMaximumSize(QtCore.QSize(80, 80))
        self.user_btn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.user_btn.setStyleSheet("\n"
"border-radius:40px\n"
"")
        self.user_btn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/image/image/avt-df.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.user_btn.setIcon(icon4)
        self.user_btn.setIconSize(QtCore.QSize(44, 44))
        self.user_btn.setObjectName("user_btn")
        self.verticalLayout_2.addWidget(self.user_btn)
        self.horizontalLayout.addWidget(self.sidebar_menu)
        self.horizontalLayout_4.addWidget(self.sidebar)
        self.stackedWidget = QtWidgets.QStackedWidget(self.main_content)
        self.stackedWidget.setObjectName("stackedWidget")
        self.chat_page = QtWidgets.QWidget()
        self.chat_page.setObjectName("chat_page")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.chat_page)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.chat_container = QtWidgets.QWidget(self.chat_page)
        self.chat_container.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.chat_container.setObjectName("chat_container")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.chat_container)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.chat_sidebar = QtWidgets.QWidget(self.chat_container)
        self.chat_sidebar.setMaximumSize(QtCore.QSize(300, 16777215))
        self.chat_sidebar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.chat_sidebar.setObjectName("chat_sidebar")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.chat_sidebar)
        self.verticalLayout_5.setContentsMargins(0, 16, 12, 0)
        self.verticalLayout_5.setSpacing(12)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.chat_sidebar_top = QtWidgets.QWidget(self.chat_sidebar)
        self.chat_sidebar_top.setMaximumSize(QtCore.QSize(16777215, 99))
        self.chat_sidebar_top.setStyleSheet("border-bottom:")
        self.chat_sidebar_top.setObjectName("chat_sidebar_top")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.chat_sidebar_top)
        self.verticalLayout_4.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame = QtWidgets.QFrame(self.chat_sidebar_top)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 40))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.chat__sidebar_title = QtWidgets.QLabel(self.frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.chat__sidebar_title.setFont(font)
        self.chat__sidebar_title.setObjectName("chat__sidebar_title")
        self.horizontalLayout_2.addWidget(self.chat__sidebar_title)
        self.on_new_message = QtWidgets.QPushButton(self.frame)
        self.on_new_message.setMinimumSize(QtCore.QSize(36, 36))
        self.on_new_message.setMaximumSize(QtCore.QSize(36, 36))
        self.on_new_message.setStyleSheet("border:none;\n"
"border-radius:44px")
        self.on_new_message.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-plus-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_new_message.setIcon(icon5)
        self.on_new_message.setIconSize(QtCore.QSize(32, 32))
        self.on_new_message.setObjectName("on_new_message")
        self.horizontalLayout_2.addWidget(self.on_new_message)
        self.verticalLayout_4.addWidget(self.frame)
        self.search_input = QtWidgets.QLineEdit(self.chat_sidebar_top)
        self.search_input.setMinimumSize(QtCore.QSize(0, 44))
        self.search_input.setStyleSheet("border-radius: 22px;\n"
"background-color:#f2f2f2;")
        self.search_input.setObjectName("search_input")
        self.verticalLayout_4.addWidget(self.search_input)
        self.verticalLayout_5.addWidget(self.chat_sidebar_top)
        self.user_chat_view = QtWidgets.QWidget(self.chat_sidebar)
        self.user_chat_view.setObjectName("user_chat_view")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.user_chat_view)
        self.verticalLayout_10.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.friend_chat_card = QtWidgets.QWidget(self.user_chat_view)
        self.friend_chat_card.setMinimumSize(QtCore.QSize(0, 64))
        self.friend_chat_card.setMaximumSize(QtCore.QSize(16777215, 64))
        self.friend_chat_card.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.friend_chat_card.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.friend_chat_card.setStyleSheet("")
        self.friend_chat_card.setObjectName("friend_chat_card")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.friend_chat_card)
        self.horizontalLayout_6.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_6.setSpacing(0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setHorizontalSpacing(12)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.friend_avt = QtWidgets.QLabel(self.friend_chat_card)
        self.friend_avt.setStyleSheet("border-image:url(:/image/image/avt.jpg);\n"
"max-width:44px;\n"
"max-height:44px;\n"
"min-width:44px;\n"
"min-height:44px;\n"
"border-radius:22px")
        self.friend_avt.setText("")
        self.friend_avt.setObjectName("friend_avt")
        self.gridLayout.addWidget(self.friend_avt, 0, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.friend_chat_card)
        self.widget_3.setStyleSheet("background-color:transparent")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.friend_name = QtWidgets.QLabel(self.widget_3)
        self.friend_name.setStyleSheet("font-size:16px;\n"
"font-weight:500;\n"
"background-color:transparent")
        self.friend_name.setObjectName("friend_name")
        self.verticalLayout_6.addWidget(self.friend_name)
        self.friend_last_message = QtWidgets.QLabel(self.widget_3)
        self.friend_last_message.setStyleSheet("color:#65676b;\n"
"font-size:12px;\n"
"background-color:transparent")
        self.friend_last_message.setTextFormat(QtCore.Qt.AutoText)
        self.friend_last_message.setScaledContents(False)
        self.friend_last_message.setWordWrap(False)
        self.friend_last_message.setIndent(-1)
        self.friend_last_message.setOpenExternalLinks(False)
        self.friend_last_message.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.friend_last_message.setObjectName("friend_last_message")
        self.verticalLayout_6.addWidget(self.friend_last_message)
        self.gridLayout.addWidget(self.widget_3, 0, 1, 1, 1)
        self.friend_time_last_message = QtWidgets.QLabel(self.friend_chat_card)
        self.friend_time_last_message.setStyleSheet("color:#65676b;\n"
"font-size:12px;\n"
"")
        self.friend_time_last_message.setObjectName("friend_time_last_message")
        self.gridLayout.addWidget(self.friend_time_last_message, 0, 2, 1, 1)
        self.horizontalLayout_6.addLayout(self.gridLayout)
        self.verticalLayout_10.addWidget(self.friend_chat_card)
        self.widget_2 = QtWidgets.QWidget(self.user_chat_view)
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.verticalLayout_10.addWidget(self.widget_2)
        self.verticalLayout_5.addWidget(self.user_chat_view)
        self.horizontalLayout_3.addWidget(self.chat_sidebar)
        self.chat_content = QtWidgets.QWidget(self.chat_container)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        self.chat_content.setFont(font)
        self.chat_content.setObjectName("chat_content")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.chat_content)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.chat_nav_user = QtWidgets.QWidget(self.chat_content)
        self.chat_nav_user.setMinimumSize(QtCore.QSize(0, 80))
        self.chat_nav_user.setMaximumSize(QtCore.QSize(16777215, 80))
        self.chat_nav_user.setStyleSheet("")
        self.chat_nav_user.setObjectName("chat_nav_user")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.chat_nav_user)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.friend_chat_acrtive = QtWidgets.QWidget(self.chat_nav_user)
        self.friend_chat_acrtive.setMaximumSize(QtCore.QSize(16777215, 56))
        self.friend_chat_acrtive.setObjectName("friend_chat_acrtive")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.friend_chat_acrtive)
        self.horizontalLayout_7.setSpacing(12)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.friend_avt_active = QtWidgets.QLabel(self.friend_chat_acrtive)
        self.friend_avt_active.setMinimumSize(QtCore.QSize(32, 32))
        self.friend_avt_active.setMaximumSize(QtCore.QSize(32, 32))
        self.friend_avt_active.setStyleSheet("border-image: url(:/image/image/avt.jpg);\n"
"max-width:32px;\n"
"max-height:32px;\n"
"min-width:32px;\n"
"min-height:32px;\n"
"border-radius:16px")
        self.friend_avt_active.setText("")
        self.friend_avt_active.setObjectName("friend_avt_active")
        self.horizontalLayout_7.addWidget(self.friend_avt_active)
        self.frame_2 = QtWidgets.QFrame(self.friend_chat_acrtive)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.friend_chat_name_active = QtWidgets.QLabel(self.frame_2)
        self.friend_chat_name_active.setStyleSheet("font-size:16px;\n"
"font-weight:500;")
        self.friend_chat_name_active.setObjectName("friend_chat_name_active")
        self.verticalLayout_8.addWidget(self.friend_chat_name_active)
        self.friend_on_active = QtWidgets.QLabel(self.frame_2)
        self.friend_on_active.setStyleSheet("color:#65676b;\n"
"font-size:12px")
        self.friend_on_active.setTextFormat(QtCore.Qt.AutoText)
        self.friend_on_active.setScaledContents(True)
        self.friend_on_active.setWordWrap(False)
        self.friend_on_active.setIndent(-1)
        self.friend_on_active.setOpenExternalLinks(False)
        self.friend_on_active.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.friend_on_active.setObjectName("friend_on_active")
        self.verticalLayout_8.addWidget(self.friend_on_active)
        self.horizontalLayout_7.addWidget(self.frame_2)
        self.horizontalLayout_12.addWidget(self.friend_chat_acrtive)
        self.frame_3 = QtWidgets.QFrame(self.chat_nav_user)
        self.frame_3.setStyleSheet("")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.widget = QtWidgets.QWidget(self.frame_3)
        self.widget.setStyleSheet("QPushButton {\n"
"    border-radius:26px;\n"
"    \n"
"}\n"
"QPushButton:hover {\n"
"    background-color:#f5f5f5\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_13.setSpacing(0)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.on_phone_call = QtWidgets.QPushButton(self.widget)
        self.on_phone_call.setMinimumSize(QtCore.QSize(52, 52))
        self.on_phone_call.setMaximumSize(QtCore.QSize(52, 52))
        self.on_phone_call.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_phone_call.setStyleSheet("")
        self.on_phone_call.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icon/icon/icon-phone.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_phone_call.setIcon(icon6)
        self.on_phone_call.setIconSize(QtCore.QSize(32, 32))
        self.on_phone_call.setObjectName("on_phone_call")
        self.horizontalLayout_13.addWidget(self.on_phone_call)
        self.on_video_call = QtWidgets.QPushButton(self.widget)
        self.on_video_call.setMinimumSize(QtCore.QSize(52, 52))
        self.on_video_call.setMaximumSize(QtCore.QSize(52, 52))
        self.on_video_call.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_video_call.setStyleSheet("")
        self.on_video_call.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/icon/icon/icon-video-call.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_video_call.setIcon(icon7)
        self.on_video_call.setIconSize(QtCore.QSize(32, 32))
        self.on_video_call.setObjectName("on_video_call")
        self.horizontalLayout_13.addWidget(self.on_video_call)
        self.on_info_chat = QtWidgets.QPushButton(self.widget)
        self.on_info_chat.setMinimumSize(QtCore.QSize(52, 52))
        self.on_info_chat.setMaximumSize(QtCore.QSize(52, 52))
        self.on_info_chat.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_info_chat.setStyleSheet("")
        self.on_info_chat.setText("")
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(":/icon/icon/icon-info.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_info_chat.setIcon(icon8)
        self.on_info_chat.setIconSize(QtCore.QSize(32, 32))
        self.on_info_chat.setObjectName("on_info_chat")
        self.horizontalLayout_13.addWidget(self.on_info_chat)
        self.horizontalLayout_8.addWidget(self.widget, 0, QtCore.Qt.AlignRight)
        self.horizontalLayout_12.addWidget(self.frame_3)
        self.verticalLayout_7.addWidget(self.chat_nav_user)
        self.chat_main_content = QtWidgets.QWidget(self.chat_content)
        self.chat_main_content.setObjectName("chat_main_content")
        self.widget_4 = QtWidgets.QWidget(self.chat_main_content)
        self.widget_4.setGeometry(QtCore.QRect(10, 70, 801, 81))
        self.widget_4.setObjectName("widget_4")
        self.friend_avt_2 = QtWidgets.QLabel(self.widget_4)
        self.friend_avt_2.setGeometry(QtCore.QRect(10, 45, 32, 32))
        self.friend_avt_2.setMinimumSize(QtCore.QSize(32, 32))
        self.friend_avt_2.setMaximumSize(QtCore.QSize(32, 32))
        self.friend_avt_2.setStyleSheet("border-image: url(:/image/image/avt.jpg);\n"
"max-width:32px;\n"
"max-height:32px;\n"
"min-width:32px;\n"
"min-height:32px;\n"
"border-radius:16px")
        self.friend_avt_2.setText("")
        self.friend_avt_2.setObjectName("friend_avt_2")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(50, 0, 71, 36))
        self.label.setStyleSheet("padding:4px 12px;\n"
"background:#fff;\n"
"border:1px solid #c4c4c4;\n"
"border-radius:18px;\n"
"font-size:12px")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.widget_4)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 101, 36))
        self.label_2.setStyleSheet("padding:4px 12px;\n"
"background:#fff;\n"
"border:1px solid #c4c4c4;\n"
"border-radius:18px;\n"
"font-size:12px")
        self.label_2.setObjectName("label_2")
        self.widget_5 = QtWidgets.QWidget(self.chat_main_content)
        self.widget_5.setGeometry(QtCore.QRect(10, 200, 801, 371))
        self.widget_5.setObjectName("widget_5")
        self.label_5 = QtWidgets.QLabel(self.widget_5)
        self.label_5.setGeometry(QtCore.QRect(720, 0, 70, 36))
        self.label_5.setStyleSheet("padding:4px 12px;\n"
"background:#f5f5f5;\n"
"border-radius:16px;\n"
"font-size:12px")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.widget_5)
        self.label_6.setGeometry(QtCore.QRect(710, 40, 80, 36))
        self.label_6.setStyleSheet("padding:4px 12px;\n"
"background:#f5f5f5;\n"
"border-radius:16px;\n"
"font-size:12px")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.widget_5)
        self.label_7.setGeometry(QtCore.QRect(315, 80, 470, 290))
        self.label_7.setStyleSheet("background-image: url(:/image/image/auth-apppng.png);\n"
"\n"
"border-radius:16px")
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.friend_time_last_message_2 = QtWidgets.QLabel(self.chat_main_content)
        self.friend_time_last_message_2.setGeometry(QtCore.QRect(10, 30, 791, 31))
        self.friend_time_last_message_2.setStyleSheet("color:#65676b;\n"
"font-size:12px;\n"
"")
        self.friend_time_last_message_2.setAlignment(QtCore.Qt.AlignCenter)
        self.friend_time_last_message_2.setObjectName("friend_time_last_message_2")
        self.friend_time_last_message_3 = QtWidgets.QLabel(self.chat_main_content)
        self.friend_time_last_message_3.setGeometry(QtCore.QRect(10, 160, 791, 31))
        self.friend_time_last_message_3.setStyleSheet("color:#65676b;\n"
"font-size:12px;\n"
"")
        self.friend_time_last_message_3.setAlignment(QtCore.Qt.AlignCenter)
        self.friend_time_last_message_3.setObjectName("friend_time_last_message_3")
        self.verticalLayout_7.addWidget(self.chat_main_content)
        self.chat_input = QtWidgets.QWidget(self.chat_content)
        self.chat_input.setMinimumSize(QtCore.QSize(0, 80))
        self.chat_input.setMaximumSize(QtCore.QSize(16777215, 80))
        self.chat_input.setObjectName("chat_input")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.chat_input)
        self.horizontalLayout_9.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.on_send_heart = QtWidgets.QPushButton(self.chat_input)
        self.on_send_heart.setMinimumSize(QtCore.QSize(44, 44))
        self.on_send_heart.setMaximumSize(QtCore.QSize(44, 44))
        self.on_send_heart.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_send_heart.setStyleSheet("border:none;\n"
"border-radius:44px")
        self.on_send_heart.setText("")
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-heart-64.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_send_heart.setIcon(icon9)
        self.on_send_heart.setIconSize(QtCore.QSize(32, 32))
        self.on_send_heart.setObjectName("on_send_heart")
        self.horizontalLayout_9.addWidget(self.on_send_heart)
        self.on_send_image = QtWidgets.QPushButton(self.chat_input)
        self.on_send_image.setMinimumSize(QtCore.QSize(44, 44))
        self.on_send_image.setMaximumSize(QtCore.QSize(44, 44))
        self.on_send_image.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_send_image.setStyleSheet("border:none;\n"
"border-radius:44px")
        self.on_send_image.setText("")
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-image-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_send_image.setIcon(icon10)
        self.on_send_image.setIconSize(QtCore.QSize(32, 32))
        self.on_send_image.setObjectName("on_send_image")
        self.horizontalLayout_9.addWidget(self.on_send_image)
        self.chat_input_input = QtWidgets.QLineEdit(self.chat_input)
        self.chat_input_input.setMinimumSize(QtCore.QSize(0, 44))
        self.chat_input_input.setStyleSheet("border-radius: 22px;\n"
"background-color:#f2f2f2;")
        self.chat_input_input.setObjectName("chat_input_input")
        self.horizontalLayout_9.addWidget(self.chat_input_input)
        self.on_send_message = QtWidgets.QPushButton(self.chat_input)
        self.on_send_message.setMinimumSize(QtCore.QSize(44, 44))
        self.on_send_message.setMaximumSize(QtCore.QSize(44, 44))
        self.on_send_message.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.on_send_message.setStyleSheet("border:none;\n"
"border-radius:44px")
        self.on_send_message.setText("")
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(":/icon/icon/icons8-enter-mac-key-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.on_send_message.setIcon(icon11)
        self.on_send_message.setIconSize(QtCore.QSize(36, 36))
        self.on_send_message.setObjectName("on_send_message")
        self.horizontalLayout_9.addWidget(self.on_send_message)
        self.verticalLayout_7.addWidget(self.chat_input)
        self.horizontalLayout_3.addWidget(self.chat_content)
        self.horizontalLayout_5.addWidget(self.chat_container)
        self.stackedWidget.addWidget(self.chat_page)
        self.member_page = QtWidgets.QWidget()
        self.member_page.setObjectName("member_page")
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout(self.member_page)
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_4 = QtWidgets.QLabel(self.member_page)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_11.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.member_page)
        self.todo_pager = QtWidgets.QWidget()
        self.todo_pager.setObjectName("todo_pager")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.todo_pager)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_3 = QtWidgets.QLabel(self.todo_pager)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_10.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.todo_pager)
        self.horizontalLayout_4.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.main_content)
        self.hboxlayout.addWidget(self.container)
        MainWindow.setCentralWidget(self.style)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "GapiChat"))
        self.chat__sidebar_title.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt; font-weight:600;\">Chat</span></p></body></html>"))
        self.search_input.setPlaceholderText(_translate("MainWindow", "Tìm kiếm (Ctrl + K)"))
        self.friend_name.setText(_translate("MainWindow", "Đại Tướng Giáp"))
        self.friend_last_message.setText(_translate("MainWindow", "Hôm nay là thứ mấy chắc chắn là thứ 2"))
        self.friend_time_last_message.setText(_translate("MainWindow", "2 ngày"))
        self.friend_chat_name_active.setText(_translate("MainWindow", "Đại Tướng Giáp"))
        self.friend_on_active.setText(_translate("MainWindow", "Hoạt động 6p trước"))
        self.label.setText(_translate("MainWindow", "Hello!"))
        self.label_2.setText(_translate("MainWindow", "How are you?"))
        self.label_5.setText(_translate("MainWindow", "I\'m fine"))
        self.label_6.setText(_translate("MainWindow", "And you?"))
        self.friend_time_last_message_2.setText(_translate("MainWindow", "Tháng 7 12, 2022 7:23 chiều"))
        self.friend_time_last_message_3.setText(_translate("MainWindow", "Tháng 7 16, 2022 4:12 sáng"))
        self.chat_input_input.setPlaceholderText(_translate("MainWindow", "Tìm kiếm (Ctrl + K)"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; color:#ff5500;\">MEMBER PAGE</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:72pt; font-weight:600; color:#ff5500;\">TODO PAGE</span></p></body></html>"))
